### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by yqyy1989** [ircykk/allegro-api#8]
Hello, thanks for your project. Today I installed the project according to the installation guide, but I met a problem when I tried to run my program.  I always get the error 

> throw new PuliUnavailableException('Puli Factory is not available');
So could you please tell me how to fix the problem?
Thanks in advance.

**Comment by ircykk** [comment]
Hello,
missing HTTP client, installing it should fix the problem:
`composer require php-http/guzzle6-adapter "^1.1"`

**Comment by yqyy1989** [comment]
Hello, after I installed php-http/guzzle6-adapter, the problem is still there. 
Here is my composer.json
{
    "require": {
        "ircykk/allegro-api" : ">=1.0",
        "php-http/guzzle6-adapter" : "^1.1",
        "topthink/think-image": "^1.0",
        "topthink/think-captcha": "1.*",
        "phpoffice/phpspreadsheet" : "1.3.*",
        "google/cloud-translate" : "1.2.3"
    }
}

**Comment by yqyy1989** [comment]
Hello, now I wanna try to use your sdk to upload products, please help me.

**Comment by ircykk** [comment]
Install puli plugin:
`composer require puli/composer-plugin`
